'use client';

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Card, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { NotificationCard } from '@/components/entities/notifications/notification-card';
import { NotificationCardSkeleton } from '@/components/entities/notifications/notification-card-skeleton';
import { useNotificationsQuery } from '@/features/notifications/api/use-notifications';

const NOTIFICATION_SKELETON_COUNT = 5;

export default function NotificationsPage() {
  const notificationsQuery = useNotificationsQuery();

  const notifications = notificationsQuery.data ?? [];
  const loading = notificationsQuery.isLoading;
  const errorMessage = notificationsQuery.error instanceof Error
    ? notificationsQuery.error.message
    : null;

  return (
    <main className="min-h-screen px-6 py-12 md:px-12">
      <div className="mx-auto flex max-w-4xl flex-col gap-8">
        <section className="flex flex-col gap-1">
          <h1 className="font-heading text-3xl font-semibold text-foreground">
            Notifications
          </h1>
          <p className="text-sm text-muted-foreground">
            Review issue updates generated by asynchronous backend workflows.
          </p>
        </section>

        {errorMessage ? (
          <Alert variant="destructive">
            <AlertTitle>Could not load notifications</AlertTitle>
            <AlertDescription>{errorMessage}</AlertDescription>
          </Alert>
        ) : null}

        {loading ? (
          <section className="grid grid-cols-1 gap-4">
            {Array.from({ length: NOTIFICATION_SKELETON_COUNT }, (_, index) => (
              <NotificationCardSkeleton key={index} />
            ))}
          </section>
        ) : null}

        {!loading && notifications.length === 0 ? (
          <Card>
            <CardHeader>
              <CardTitle>No notifications yet</CardTitle>
              <CardDescription>
                Create or update assigned issues to generate notifications.
              </CardDescription>
            </CardHeader>
          </Card>
        ) : null}

        {!loading && notifications.length > 0 ? (
          <section className="grid grid-cols-1 gap-4">
            {notifications.map((notification) => (
              <NotificationCard
                key={notification.id}
                notification={notification}
              />
            ))}
          </section>
        ) : null}
      </div>
    </main>
  );
}
